### ISSUE TITLE
Report issue for `dataclass-wizard` on usage with `typing.Literal` type hint

### ISSUE THREAD

**Issue by mikeweltevrede** [mikeweltevrede/finding-the-mole#51]
When loading from a YAML file, `YAMLWizard` cannot handle the `typing.Literal` type hint. Consider the example below, where it would only recognize `str | int`.

Used version: `dataclass-wizard==0.22.3` (latest).

Minimal working example:
```
import tempfile
from dataclasses import dataclass
from pathlib import Path

@dataclass
class Context(YAMLWizard):
    literal_or_int: Literal["value"] | int

with tempfile.TemporaryDirectory() as tmp_path:
    config_path = Path(tmp_path) / "config.yml"
    with open(config_path, "w") as stream:
        stream.write("literal_or_int: value")
        
    Context.from_yaml_file(file=str(config_path))
```

Resulting error:
```
Traceback (most recent call last):
  File "data_preprocessing.py", line 193, in <module>
    Context.from_yaml_file(file=str(config_path))
  File ".venv\Lib\site-packages\dataclass_wizard\wizard_mixins.py", line 147, in from_yaml_file
    return cls.from_yaml(in_file, decoder=decoder,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\dataclass_wizard\wizard_mixins.py", line 136, in from_yaml
    return fromdict(cls, o) if isinstance(o, dict) else fromlist(cls, o)
           ^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\dataclass_wizard\loaders.py", line 536, in fromdict
    return load(d)
           ^^^^^^^
  File ".venv\Lib\site-packages\dataclass_wizard\loaders.py", line 619, in cls_fromdict
    cls_kwargs[field_name] = field_to_parser[field_name](
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv\Lib\site-packages\dataclass_wizard\parsers.py", line 250, in __call__
    raise ParseError(
dataclass_wizard.errors.ParseError: Failure parsing field `literal_or_int` in class `Context`. Expected a type [typing.Literal['value'], <class 'int'>], got str.
  value: 'value'
  error: Object was not in any of Union types
  tag_key: '__tag__'
  json_object: '{"literal_or_int": "value"}'
```

**Comment by mikeweltevrede** [comment]
See https://github.com/rnag/dataclass-wizard/issues/67

**Comment by mikeweltevrede** [comment]
PR raised, see https://github.com/rnag/dataclass-wizard/pull/111
